export type Dept = "leadership" | "engineering" | "product" | "gtm";

export type TeamMember = {
  name: string;
  role: string;
  dept: Dept;
  deptLabel: string;
  emoji: string;
  initials: string;
  noodleType: string;
  bio: string[];
  tags: string[];
  email: string;
  twitter: string;
};

export const DEPT_FILTERS: { id: "all" | Dept; label: string }[] = [
  { id: "all", label: "All noodles" },
  { id: "leadership", label: "Leadership" },
  { id: "engineering", label: "Engineering" },
  { id: "product", label: "Product & Design" },
  { id: "gtm", label: "GTM & Community" },
];

export const TEAM: TeamMember[] = [
  {
    name: "Al Dente",
    role: "CEO & Co-founder",
    dept: "leadership",
    deptLabel: "Leadership",
    emoji: "🫕",
    initials: "AD",
    noodleType: "fettuccine",
    bio: [
      "Al came from a background in distributed systems at a major cloud provider, where he spent four years making other people's pipelines not catch fire. He left to build n00dles after the third time in a year he watched a team abandon a perfectly good AI project because the orchestration layer was unmaintainable.",
      "He believes strongly that developer tools should feel like a warm bowl of soup — comforting, reliable, and exactly what you needed without having to explain why. He makes a very good carbonara and will tell you about it unprompted.",
    ],
    tags: ["distributed systems", "python", "open source", "pasta evangelist"],
    email: "al.dente@n00dles.com",
    twitter: "@aldente_dev",
  },
  {
    name: "Ramen Dass",
    role: "CTO & Co-founder",
    dept: "leadership",
    deptLabel: "Leadership",
    emoji: "🍜",
    initials: "RD",
    noodleType: "tonkotsu ramen",
    bio: [
      "Ramen built his first LLM wrapper in 2022, his second in early 2023, threw both away, and decided the problem wasn't his code — it was everyone's code. A former ML infrastructure lead, he's the reason n00dles has typed I/O contracts and zero magic in its internals.",
      "His personal philosophy: if you can't explain to a junior engineer exactly what your framework does in every case, your framework is wrong. He applies this to n00dles ruthlessly and to his ramen orders with equal intensity.",
    ],
    tags: ["ml infrastructure", "llm systems", "rust", "type theory", "ramen connoisseur"],
    email: "ramen@n00dles.com",
    twitter: "@ramendass",
  },
  {
    name: "Pho Nguyen",
    role: "VP Engineering",
    dept: "leadership",
    deptLabel: "Leadership",
    emoji: "🥣",
    initials: "PN",
    noodleType: "pho bò",
    bio: [
      "Pho runs engineering with the calm precision of someone who has seen every type of system failure and stopped being surprised by any of them. She joined n00dles after leading platform engineering at a fintech company where she processed 40 million transactions a day on infrastructure she'd built from scratch.",
      "Her first month at n00dles, she rewrote the async worker pool and reduced median pipeline latency by 60%. She said it was a Tuesday.",
    ],
    tags: ["platform engineering", "async python", "k8s", "distributed systems"],
    email: "pho@n00dles.com",
    twitter: "@phonguyen_eng",
  },
  {
    name: "Vermicelli Ray",
    role: "Head of Product",
    dept: "product",
    deptLabel: "Product & Design",
    emoji: "🫙",
    initials: "VR",
    noodleType: "rice vermicelli",
    bio: [
      "Vermicelli — Vermi to the team — has a rare combination of deep technical knowledge and genuine obsession with user experience. She spent three years at a developer tools company watching engineers fight with products that didn't respect their time, and decided to fix that from the product side.",
      "She runs weekly sessions where the whole team watches new users try n00dles for the first time. It is uncomfortable. It has made the product significantly better.",
    ],
    tags: ["developer experience", "product strategy", "user research", "api design"],
    email: "vermi@n00dles.com",
    twitter: "@vermicelli_ray",
  },
  {
    name: "Lo Mein",
    role: "Head of Design",
    dept: "product",
    deptLabel: "Product & Design",
    emoji: "🎨",
    initials: "LM",
    noodleType: "lo mein",
    bio: [
      "Lo is the reason n00dles looks the way it does. She came from a studio background, then spent two years designing developer tools at a Series B company, where she learned that engineers are the hardest and most rewarding design audience: they will instantly spot anything fake, anything slow, anything that gets between them and what they're trying to do.",
      "She designed the entire n00dles visual system in a single weekend and shipped it. The yellow was her idea. Everyone else was afraid of it. She was right.",
    ],
    tags: ["design systems", "motion design", "developer tools", "figma", "typography"],
    email: "lo@n00dles.com",
    twitter: "@lo_mein_design",
  },
  {
    name: "Udon Price",
    role: "Lead Infrastructure Engineer",
    dept: "engineering",
    deptLabel: "Engineering",
    emoji: "⚙️",
    initials: "UP",
    noodleType: "thick udon",
    bio: [
      "Udon owns everything that has to keep running when someone is asleep. The state store, the worker pool, the deploy tooling, the monitoring stack. He has a rule: every system he builds must be explainable to a non-engineer in under two minutes. This has made him an unusually good infrastructure engineer.",
      "He previously ran infrastructure at a high-frequency trading firm and still finds production web services refreshingly slow-paced.",
    ],
    tags: ["infrastructure", "redis", "docker", "k8s", "observability"],
    email: "udon@n00dles.com",
    twitter: "@udonprice",
  },
  {
    name: "Pad Thai-ler",
    role: "Senior ML Engineer",
    dept: "engineering",
    deptLabel: "Engineering",
    emoji: "🧠",
    initials: "PT",
    noodleType: "pad thai",
    bio: [
      'Pad joined n00dles after a PhD in NLP that he describes as "four years of making large models do small things correctly." He works on the provider abstraction layer, the token budget management system, and the smart retry heuristics that know when an LLM failure is transient vs structural.',
      'He is deeply suspicious of frameworks that call themselves "intelligent" and will explain why at any opportunity. His code is extremely well-commented.',
    ],
    tags: ["nlp", "llm evaluation", "prompt engineering", "pytorch", "ml systems"],
    email: "pad@n00dles.com",
    twitter: "@padthayler",
  },
  {
    name: "Soba Chen",
    role: "Backend Engineer",
    dept: "engineering",
    deptLabel: "Engineering",
    emoji: "🔧",
    initials: "SC",
    noodleType: "cold soba",
    bio: [
      "Soba owns the pipeline executor — the core runtime loop that turns your agent chain definition into actual LLM calls in the right order with the right state. She has rewritten it three times, each time making it faster and more legible, and she will probably rewrite it again.",
      "She previously worked at a database company and has opinions about consistency models that she will share with you whether you asked or not. Useful opinions, though.",
    ],
    tags: ["python", "asyncio", "system design", "databases", "testing"],
    email: "soba@n00dles.com",
    twitter: "@sobachen_dev",
  },
  {
    name: "Orzo Kim",
    role: "Frontend Engineer",
    dept: "engineering",
    deptLabel: "Engineering",
    emoji: "✨",
    initials: "OK",
    noodleType: "orzo",
    bio: [
      "Orzo built the visual pipeline debugger — the feature most users say they didn't know they needed until they couldn't live without it. She's a frontend engineer who cares deeply about performance, and will send you a Lighthouse report for any webpage you show her within 30 seconds, unprompted.",
      "She chose orzo as her noodle type because it is misunderstood, technically a pasta, and underrated. She felt seen.",
    ],
    tags: ["react", "typescript", "data visualization", "web performance", "accessibility"],
    email: "orzo@n00dles.com",
    twitter: "@orzokimdev",
  },
  {
    name: "Fettuccine Romano",
    role: "DevRel & Developer Advocate",
    dept: "gtm",
    deptLabel: "GTM & Community",
    emoji: "📣",
    initials: "FR",
    noodleType: "fettuccine alfredo",
    bio: [
      "Fett is the reason you've probably already heard of n00dles. He writes the blog posts that engineers actually read, gives talks that don't feel like product pitches, and runs the Discord with the energy of someone who genuinely loves the community he's in — because he does.",
      "He spent five years as a backend engineer before moving to DevRel, which means he can debug your pipeline AND explain why it broke in a way that's actually useful. He streams himself building with n00dles every Thursday.",
    ],
    tags: ["developer relations", "technical writing", "community", "public speaking"],
    email: "fett@n00dles.com",
    twitter: "@fettuccine_dev",
  },
  {
    name: "Linguine Cross",
    role: "Head of Partnerships",
    dept: "gtm",
    deptLabel: "GTM & Community",
    emoji: "🤝",
    initials: "LC",
    noodleType: "linguine",
    bio: [
      "Linguine runs all of n00dles' relationships with LLM providers, cloud platforms, and the ecosystem of tools that integrate with n00dles. She has a background in business development at developer tool companies and understands that the best partnerships are the ones where both sides ship something the other couldn't have shipped alone.",
      "She negotiated n00dles' first official provider integrations with three major LLM companies in the same week. She makes it look easy and will not tell you how she does it.",
    ],
    tags: ["partnerships", "biz dev", "ecosystem", "developer platforms"],
    email: "linguine@n00dles.com",
    twitter: "@linguinecross",
  },
  {
    name: "Angel Hair-ris",
    role: "Community Manager",
    dept: "gtm",
    deptLabel: "GTM & Community",
    emoji: "💬",
    initials: "AH",
    noodleType: "angel hair",
    bio: [
      "Angel runs the n00dles Discord, forum, and the weekly community call that somehow has a 40% return rate — unusually high for an open source project. She has a background in community building for developer tools and believes the difference between a good open source project and a great one is almost entirely the community around it.",
      "She is also the one who enforces the rule that every new Discord member must pick their noodle type in #introductions. This is non-negotiable.",
    ],
    tags: ["community building", "discord", "content moderation", "developer ecosystems"],
    email: "angel@n00dles.com",
    twitter: "@angelharris_dev",
  },
  {
    name: "Rigatoni Marsh",
    role: "Security Engineer",
    dept: "engineering",
    deptLabel: "Engineering",
    emoji: "🛡️",
    initials: "RM",
    noodleType: "rigatoni",
    bio: [
      'Rigatoni joined n00dles after working in application security at a financial institution where the threat model was "assume someone very smart is actively trying to break everything." He brought that same energy to n00dles.',
      "He owns the security model for how n00dles handles credentials, secrets, and API keys in deployed pipelines. He also runs the bug bounty program and personally responds to every valid security report within 24 hours. He chose rigatoni because it is structurally rigid and holds things together. Nobody argued.",
    ],
    tags: ["application security", "threat modeling", "secrets management", "cryptography"],
    email: "rigs@n00dles.com",
    twitter: "@rigatonimarsh",
  },
  {
    name: "Bucatini Bell",
    role: "Technical Writer",
    dept: "product",
    deptLabel: "Product & Design",
    emoji: "📝",
    initials: "BB",
    noodleType: "bucatini",
    bio: [
      'Bucatini wrote the docs that made developers say "oh, this actually makes sense." She has a rule that no documentation page should take longer to read than it takes to brew a cup of tea, and another rule that every code example must be runnable without modification.',
      "She was previously a backend engineer who realized she spent more time writing internal documentation than writing code, decided that was actually her calling, and has not looked back. She is the reason the n00dles quickstart works in under 5 minutes for 94% of users who try it.",
    ],
    tags: ["technical writing", "api documentation", "developer education", "python"],
    email: "buca@n00dles.com",
    twitter: "@bucatinibell",
  },
  {
    name: "Laksa Patel",
    role: "Data Engineer",
    dept: "engineering",
    deptLabel: "Engineering",
    emoji: "📊",
    initials: "LP",
    noodleType: "laksa lemak",
    bio: [
      "Laksa owns everything to do with how n00dles measures itself: the telemetry pipeline, the usage analytics, the dashboards that tell the team what's actually being used vs what they think is being used. The difference, she will tell you, is always surprising.",
      "She comes from a data engineering background at a startup that scaled from 0 to 10 million users, which taught her that data infrastructure built for current scale will fail exactly when you need it most. She builds n00dles' data systems for 10x what they need today.",
    ],
    tags: ["data engineering", "python", "dbt", "event tracking", "analytics"],
    email: "laksa@n00dles.com",
    twitter: "@laksapatel_data",
  },
];
